/**
 * Prisma Seed — Core Master Data
 *
 * Source of truth: reference_source/import/ (generated by TASK-008 pipeline)
 * Manifest hash:   ef0589fbafc22afbb1ee21556d0de615cf1e8df3092216622ad015f5a4fc4a7d
 *
 * Seeds the following entities from APPROVED reference data only:
 *   - Permissions (from ROLE_PERMISSION.md)
 *   - Roles       (SUPER_ADMIN, ADMIN, MARKETING)
 *   - RolePermissions (matrix from ROLE_PERMISSION.md §4)
 *   - BPRs
 *   - Products
 *   - CreditParameters
 *   - FeeParameters
 *   - InsuranceRates
 *   - PaymentOffices
 *   - BusinessRuleVersion (BR-1.0)
 *   - ParameterVersion    (v1.0 per product)
 *
 * Rules:
 *   - No data is invented or approximated.
 *   - All numeric financial values read directly from approved JSON artifacts.
 *   - Idempotent: uses upsert on unique keys, safe to re-run.
 */

import { PrismaClient } from "@prisma/client";
import * as fs from "fs";
import * as path from "path";

const prisma = new PrismaClient();

// ---------------------------------------------------------------------------
// Load approved import artifacts
// ---------------------------------------------------------------------------
const IMPORT_DIR = path.resolve(__dirname, "../reference_source/import");
const MANIFEST_PATH = path.join(IMPORT_DIR, "manifest.json");

function loadImport<T>(filename: string): T[] {
  const filePath = path.join(IMPORT_DIR, filename);
  if (!fs.existsSync(filePath)) {
    throw new Error(
      `BLOCKED: Approved import file not found: ${filePath}. Run the import pipeline first.`
    );
  }
  return JSON.parse(fs.readFileSync(filePath, "utf-8")) as T[];
}

function verifyManifest() {
  if (!fs.existsSync(MANIFEST_PATH)) {
    throw new Error(
      "BLOCKED: manifest.json not found in reference_source/import/. Run the import pipeline first."
    );
  }
  const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, "utf-8"));
  if (manifest.validationStatus !== "APPROVED") {
    throw new Error(
      `BLOCKED: Import manifest status is "${manifest.validationStatus}", not "APPROVED". Validation must pass before seeding.`
    );
  }
  console.log(`✅ Manifest verified — Source hash: ${manifest.documentHash}`);
  console.log(`   Pipeline version: ${manifest.pipelineVersion}`);
  console.log(`   Extracted at:     ${manifest.extractedAt}`);
  return manifest;
}

// ---------------------------------------------------------------------------
// Permissions — canonical from ROLE_PERMISSION.md
// ---------------------------------------------------------------------------
const PERMISSIONS = [
  // Authentication
  { code: "AUTH_LOGIN",           name: "Login",                           module: "AUTH" },
  { code: "AUTH_LOGOUT",          name: "Logout",                          module: "AUTH" },
  { code: "AUTH_CHANGE_PASSWORD", name: "Ubah password sendiri",           module: "AUTH" },
  { code: "AUTH_RESET_PASSWORD",  name: "Reset password user lain",        module: "AUTH" },
  { code: "PROFILE_VIEW",         name: "Lihat profil sendiri",            module: "AUTH" },
  { code: "PROFILE_UPDATE",       name: "Ubah profil sendiri",             module: "AUTH" },
  // User Management
  { code: "USER_VIEW",            name: "Lihat user",                      module: "USER" },
  { code: "USER_CREATE",          name: "Buat user",                       module: "USER" },
  { code: "USER_UPDATE",          name: "Ubah user",                       module: "USER" },
  { code: "USER_DELETE",          name: "Hapus user",                      module: "USER" },
  { code: "USER_ACTIVATE",        name: "Aktifkan user",                   module: "USER" },
  { code: "USER_DEACTIVATE",      name: "Nonaktifkan user",                module: "USER" },
  { code: "USER_RESET_PASSWORD",  name: "Reset password user",             module: "USER" },
  { code: "USER_ASSIGN_ROLE",     name: "Berikan role ke user",            module: "USER" },
  // Role & Permission Management
  { code: "ROLE_VIEW",              name: "Lihat role",                    module: "ROLE" },
  { code: "ROLE_CREATE",            name: "Buat role",                     module: "ROLE" },
  { code: "ROLE_UPDATE",            name: "Ubah role",                     module: "ROLE" },
  { code: "ROLE_DELETE",            name: "Hapus role",                    module: "ROLE" },
  { code: "PERMISSION_VIEW",        name: "Lihat permission",              module: "ROLE" },
  { code: "ROLE_PERMISSION_ASSIGN", name: "Atur permission role",          module: "ROLE" },
  // Credit Calculator
  { code: "CREDIT_CALCULATE",    name: "Jalankan kalkulasi kredit",        module: "CREDIT" },
  { code: "CREDIT_VIEW_RESULT",  name: "Lihat hasil kalkulasi",            module: "CREDIT" },
  { code: "CREDIT_EXPORT",       name: "Export hasil kalkulasi",           module: "CREDIT" },
  // Simulation
  { code: "SIMULATION_VIEW",     name: "Lihat simulasi",                   module: "SIMULATION" },
  { code: "SIMULATION_CREATE",   name: "Buat simulasi",                    module: "SIMULATION" },
  { code: "SIMULATION_UPDATE",   name: "Ubah simulasi",                    module: "SIMULATION" },
  { code: "SIMULATION_DELETE",   name: "Hapus simulasi",                   module: "SIMULATION" },
  { code: "SIMULATION_EXPORT",   name: "Export simulasi",                  module: "SIMULATION" },
  // Master Data
  { code: "MASTER_VIEW",         name: "Lihat master data",                module: "MASTER" },
  { code: "MASTER_CREATE",       name: "Buat master data",                 module: "MASTER" },
  { code: "MASTER_UPDATE",       name: "Ubah master data",                 module: "MASTER" },
  { code: "MASTER_DELETE",       name: "Hapus master data",                module: "MASTER" },
  // Credit Parameters
  { code: "CREDIT_PARAMETER_VIEW",   name: "Lihat parameter kredit",       module: "CREDIT_PARAM" },
  { code: "CREDIT_PARAMETER_CREATE", name: "Buat parameter kredit",        module: "CREDIT_PARAM" },
  { code: "CREDIT_PARAMETER_UPDATE", name: "Ubah parameter kredit",        module: "CREDIT_PARAM" },
  { code: "CREDIT_PARAMETER_DELETE", name: "Hapus parameter kredit",       module: "CREDIT_PARAM" },
  // Reports
  { code: "REPORT_VIEW",         name: "Lihat laporan",                    module: "REPORT" },
  { code: "REPORT_EXPORT",       name: "Export laporan",                   module: "REPORT" },
  // Audit Trail
  { code: "AUDIT_VIEW",          name: "Lihat audit trail",                module: "AUDIT" },
  { code: "AUDIT_EXPORT",        name: "Export audit trail",               module: "AUDIT" },
] as const;

// ---------------------------------------------------------------------------
// Role-Permission matrix — from ROLE_PERMISSION.md §4
// ---------------------------------------------------------------------------
const SUPER_ADMIN_PERMISSIONS = [
  "AUTH_LOGIN", "AUTH_LOGOUT", "AUTH_CHANGE_PASSWORD", "AUTH_RESET_PASSWORD",
  "PROFILE_VIEW", "PROFILE_UPDATE",
  "USER_VIEW", "USER_CREATE", "USER_UPDATE", "USER_DELETE", "USER_ACTIVATE",
  "USER_DEACTIVATE", "USER_RESET_PASSWORD", "USER_ASSIGN_ROLE",
  "ROLE_VIEW", "ROLE_CREATE", "ROLE_UPDATE", "ROLE_DELETE",
  "PERMISSION_VIEW", "ROLE_PERMISSION_ASSIGN",
  "CREDIT_CALCULATE", "CREDIT_VIEW_RESULT", "CREDIT_EXPORT",
  "SIMULATION_VIEW", "SIMULATION_CREATE", "SIMULATION_UPDATE",
  "SIMULATION_DELETE", "SIMULATION_EXPORT",
  "MASTER_VIEW", "MASTER_CREATE", "MASTER_UPDATE", "MASTER_DELETE",
  "CREDIT_PARAMETER_VIEW", "CREDIT_PARAMETER_CREATE", "CREDIT_PARAMETER_UPDATE",
  "CREDIT_PARAMETER_DELETE",
  "REPORT_VIEW", "REPORT_EXPORT",
  "AUDIT_VIEW", "AUDIT_EXPORT",
];

const ADMIN_PERMISSIONS = [
  "AUTH_LOGIN", "AUTH_LOGOUT", "AUTH_CHANGE_PASSWORD", "AUTH_RESET_PASSWORD",
  "PROFILE_VIEW", "PROFILE_UPDATE",
  "USER_VIEW", "USER_CREATE", "USER_UPDATE", "USER_ACTIVATE",
  "USER_DEACTIVATE", "USER_RESET_PASSWORD", "USER_ASSIGN_ROLE",
  "CREDIT_CALCULATE", "CREDIT_VIEW_RESULT", "CREDIT_EXPORT",
  "SIMULATION_VIEW", "SIMULATION_CREATE", "SIMULATION_UPDATE",
  "SIMULATION_DELETE", "SIMULATION_EXPORT",
  "MASTER_VIEW", "MASTER_CREATE", "MASTER_UPDATE", "MASTER_DELETE",
  "CREDIT_PARAMETER_VIEW", "CREDIT_PARAMETER_CREATE", "CREDIT_PARAMETER_UPDATE",
  "REPORT_VIEW", "REPORT_EXPORT",
  "AUDIT_VIEW",
];

const MARKETING_PERMISSIONS = [
  "AUTH_LOGIN", "AUTH_LOGOUT", "AUTH_CHANGE_PASSWORD",
  "PROFILE_VIEW", "PROFILE_UPDATE",
  "CREDIT_CALCULATE", "CREDIT_VIEW_RESULT", "CREDIT_EXPORT",
  "SIMULATION_VIEW", "SIMULATION_CREATE", "SIMULATION_UPDATE",
  "SIMULATION_DELETE", "SIMULATION_EXPORT",
  "REPORT_VIEW", "REPORT_EXPORT",
];

// ---------------------------------------------------------------------------
// Main seed function
// ---------------------------------------------------------------------------
async function main() {
  console.log("\n🌱 Starting TASK-009 — Core Master Data Seed...\n");

  // 1. Verify approved manifest before any seeding
  const manifest = verifyManifest();

  // -------------------------------------------------------------------------
  // 2. Seed Permissions
  // -------------------------------------------------------------------------
  console.log(`\n📌 Seeding ${PERMISSIONS.length} permissions...`);
  for (const perm of PERMISSIONS) {
    await prisma.permission.upsert({
      where: { code: perm.code },
      update: { name: perm.name, module: perm.module },
      create: { code: perm.code, name: perm.name, module: perm.module },
    });
  }
  console.log(`   ✅ ${PERMISSIONS.length} permissions upserted.`);

  // -------------------------------------------------------------------------
  // 3. Seed Roles
  // -------------------------------------------------------------------------
  console.log("\n📌 Seeding roles (SUPER_ADMIN, ADMIN, MARKETING)...");
  const roles = [
    { code: "SUPER_ADMIN", name: "Super Admin",  description: "Akses penuh ke seluruh sistem" },
    { code: "ADMIN",       name: "Admin",         description: "Akses operasional sesuai scope" },
    { code: "MARKETING",   name: "Marketing",     description: "Pengguna operasional simulasi kredit" },
  ];
  const roleMap: Record<string, string> = {};
  for (const role of roles) {
    const r = await prisma.role.upsert({
      where: { code: role.code },
      update: { name: role.name, description: role.description, isActive: true },
      create: { code: role.code, name: role.name, description: role.description, isActive: true },
    });
    roleMap[role.code] = r.id;
  }
  console.log(`   ✅ 3 roles upserted.`);

  // -------------------------------------------------------------------------
  // 4. Seed Role-Permissions
  // -------------------------------------------------------------------------
  console.log("\n📌 Seeding role-permission assignments...");
  const permMap: Record<string, string> = {};
  const allPerms = await prisma.permission.findMany({ select: { id: true, code: true } });
  for (const p of allPerms) {
    permMap[p.code] = p.id;
  }

  const rolePermMatrix = [
    { roleCode: "SUPER_ADMIN", permCodes: SUPER_ADMIN_PERMISSIONS },
    { roleCode: "ADMIN",       permCodes: ADMIN_PERMISSIONS },
    { roleCode: "MARKETING",   permCodes: MARKETING_PERMISSIONS },
  ];

  let rpCount = 0;
  for (const { roleCode, permCodes } of rolePermMatrix) {
    const roleId = roleMap[roleCode];
    for (const permCode of permCodes) {
      const permId = permMap[permCode];
      if (!permId) {
        console.warn(`   ⚠️  Permission code not found: ${permCode}`);
        continue;
      }
      await prisma.rolePermission.upsert({
        where: { roleId_permissionId: { roleId, permissionId: permId } },
        update: {},
        create: { roleId, permissionId: permId },
      });
      rpCount++;
    }
  }
  console.log(`   ✅ ${rpCount} role-permission assignments upserted.`);

  // -------------------------------------------------------------------------
  // 5. Seed BPRs
  // -------------------------------------------------------------------------
  const bprData = loadImport<{ code: string; name: string; status: string }>("bpr_master.json");
  console.log(`\n📌 Seeding ${bprData.length} BPRs...`);
  const bprMap: Record<string, string> = {};
  for (const bpr of bprData) {
    const b = await prisma.bpr.upsert({
      where: { code: bpr.code },
      update: { name: bpr.name, status: bpr.status },
      create: { code: bpr.code, name: bpr.name, status: bpr.status },
    });
    bprMap[bpr.code] = b.id;
  }
  console.log(`   ✅ ${bprData.length} BPRs upserted.`);

  // -------------------------------------------------------------------------
  // 6. Seed Products
  // -------------------------------------------------------------------------
  const productData = loadImport<{
    code: string; name: string; bprCode: string; description: string; status: string;
  }>("products.json");
  console.log(`\n📌 Seeding ${productData.length} products...`);
  const productMap: Record<string, string> = {};
  for (const prod of productData) {
    const bprId = bprMap[prod.bprCode];
    if (!bprId) throw new Error(`BLOCKED: BPR not found for product "${prod.code}": bprCode="${prod.bprCode}"`);
    const p = await prisma.product.upsert({
      where: { bprId_code: { bprId, code: prod.code } },
      update: { name: prod.name, description: prod.description, status: prod.status },
      create: { bprId, code: prod.code, name: prod.name, description: prod.description, status: prod.status },
    });
    productMap[prod.code] = p.id;
  }
  console.log(`   ✅ ${productData.length} products upserted.`);

  // -------------------------------------------------------------------------
  // 7. Seed BusinessRuleVersion (BR-1.0)
  // -------------------------------------------------------------------------
  console.log("\n📌 Seeding business rule version BR-1.0...");
  await prisma.businessRuleVersion.upsert({
    where: { version: "BR-1.0" },
    update: {},
    create: {
      version: "BR-1.0",
      name: "Credit Calculator BPR — Business Rules v1.0",
      description: "Initial business rules: flat rate 10.8% p.a., DBR 90%, tenor max 120 months, principal max Rp200jt",
      status: "ACTIVE",
      effectiveFrom: new Date("2026-01-01"),
    },
  });
  console.log(`   ✅ BusinessRuleVersion BR-1.0 upserted.`);

  // -------------------------------------------------------------------------
  // 8. Seed ParameterVersions
  // -------------------------------------------------------------------------
  console.log("\n📌 Seeding parameter versions...");
  for (const prod of productData) {
    const productId = productMap[prod.code];
    await prisma.parameterVersion.upsert({
      where: { productId_version: { productId, version: "v1.0" } },
      update: {},
      create: {
        version: "v1.0",
        productId,
        description: `Initial parameter set for ${prod.name} — source: ${manifest.sourceFileName} (hash: ${manifest.documentHash.slice(0, 12)}...)`,
        effectiveFrom: new Date("2026-01-01"),
        status: "ACTIVE",
      },
    });
  }
  console.log(`   ✅ ${productData.length} parameter version(s) upserted.`);

  // -------------------------------------------------------------------------
  // 9. Seed Credit Parameters
  // -------------------------------------------------------------------------
  const creditParams = loadImport<{
    productCode: string; maximumAgeYears: number; maximumAgeMonths: number;
    maximumTenorMonths: number; maximumPrincipal: number; maximumDbr: number;
    flatAnnualRate: number; flatMonthlyRate: number; principalRoundingIncrement: number;
    installmentDeductionPeriods: number; version: string;
  }>("credit_parameters.json");
  console.log(`\n📌 Seeding ${creditParams.length} credit parameter(s)...`);
  for (const cp of creditParams) {
    const productId = productMap[cp.productCode];
    if (!productId) throw new Error(`BLOCKED: Product not found for credit param: "${cp.productCode}"`);
    // Deactivate any existing active params first (versioned)
    await prisma.creditParameter.updateMany({
      where: { productId, isActive: true },
      data: { isActive: false },
    });
    await prisma.creditParameter.create({
      data: {
        productId,
        maximumAgeYears: cp.maximumAgeYears,
        maximumAgeMonths: cp.maximumAgeMonths,
        maximumTenorMonths: cp.maximumTenorMonths,
        maximumPrincipal: cp.maximumPrincipal,
        maximumDbr: cp.maximumDbr,
        flatAnnualRate: cp.flatAnnualRate,
        flatMonthlyRate: cp.flatMonthlyRate,
        principalRoundingIncrement: cp.principalRoundingIncrement,
        installmentDeductionPeriods: cp.installmentDeductionPeriods,
        effectiveFrom: new Date("2026-01-01"),
        version: cp.version,
        isActive: true,
      },
    });
  }
  console.log(`   ✅ ${creditParams.length} credit parameter(s) seeded.`);

  // -------------------------------------------------------------------------
  // 10. Seed Fee Parameters
  // -------------------------------------------------------------------------
  const feeParams = loadImport<{
    productCode: string; adminRate: number; provisionRate: number; verificationFee: number;
    flaggingFee: number; frontingRate: number; reserveRate: number; version: string;
  }>("fee_parameters.json");
  console.log(`\n📌 Seeding ${feeParams.length} fee parameter(s)...`);
  for (const fp of feeParams) {
    const productId = productMap[fp.productCode];
    if (!productId) throw new Error(`BLOCKED: Product not found for fee param: "${fp.productCode}"`);
    await prisma.feeParameter.updateMany({
      where: { productId, isActive: true },
      data: { isActive: false },
    });
    await prisma.feeParameter.create({
      data: {
        productId,
        adminRate: fp.adminRate,
        provisionRate: fp.provisionRate,
        verificationFee: fp.verificationFee,
        flaggingFee: fp.flaggingFee,
        frontingRate: fp.frontingRate,
        reserveRate: fp.reserveRate,
        effectiveFrom: new Date("2026-01-01"),
        version: fp.version,
        isActive: true,
      },
    });
  }
  console.log(`   ✅ ${feeParams.length} fee parameter(s) seeded.`);

  // -------------------------------------------------------------------------
  // 11. Seed Payment Offices
  // -------------------------------------------------------------------------
  const paymentOffices = loadImport<{
    code: string; name: string; bprCode: string; type: string; status: string;
  }>("payment_offices.json");
  console.log(`\n📌 Seeding ${paymentOffices.length} payment offices...`);
  for (const po of paymentOffices) {
    const bprId = bprMap[po.bprCode];
    if (!bprId) throw new Error(`BLOCKED: BPR not found for payment office "${po.code}": bprCode="${po.bprCode}"`);
    await prisma.paymentOffice.upsert({
      where: { bprId_code: { bprId, code: po.code } },
      update: { name: po.name, type: po.type, status: po.status },
      create: { bprId, code: po.code, name: po.name, type: po.type, status: po.status },
    });
  }
  console.log(`   ✅ ${paymentOffices.length} payment offices upserted.`);

  // -------------------------------------------------------------------------
  // 12. Seed Insurance Rates
  // -------------------------------------------------------------------------
  const insuranceRates = loadImport<{
    productCode: string; age: number; tenorYears: number; premiumRate: number; version: string;
  }>("insurance_rates.json");
  console.log(`\n📌 Seeding ${insuranceRates.length} insurance rate rows...`);
  const effectiveFrom = new Date("2026-01-01");
  let irCount = 0;
  for (const ir of insuranceRates) {
    const productId = productMap[ir.productCode];
    if (!productId) throw new Error(`BLOCKED: Product not found for insurance rate: "${ir.productCode}"`);
    await prisma.insuranceRate.upsert({
      where: {
        productId_age_tenorYears_effectiveFrom: {
          productId,
          age: ir.age,
          tenorYears: ir.tenorYears,
          effectiveFrom,
        },
      },
      update: { premiumRate: ir.premiumRate, version: ir.version, isActive: true },
      create: {
        productId,
        age: ir.age,
        tenorYears: ir.tenorYears,
        premiumRate: ir.premiumRate,
        effectiveFrom,
        version: ir.version,
        isActive: true,
      },
    });
    irCount++;
  }
  console.log(`   ✅ ${irCount} insurance rate rows upserted.`);

  // -------------------------------------------------------------------------
  // Summary
  // -------------------------------------------------------------------------
  console.log("\n🎉 TASK-009 — Core Master Seed completed successfully!\n");
  console.log("📊 Final counts in database:");
  console.log(`   Permissions:    ${await prisma.permission.count()}`);
  console.log(`   Roles:          ${await prisma.role.count()}`);
  console.log(`   RolePermissions:${await prisma.rolePermission.count()}`);
  console.log(`   BPRs:           ${await prisma.bpr.count()}`);
  console.log(`   Products:       ${await prisma.product.count()}`);
  console.log(`   Credit Params:  ${await prisma.creditParameter.count({ where: { isActive: true } })}`);
  console.log(`   Fee Params:     ${await prisma.feeParameter.count({ where: { isActive: true } })}`);
  console.log(`   Payment Offices:${await prisma.paymentOffice.count()}`);
  console.log(`   Insurance Rates:${await prisma.insuranceRate.count({ where: { isActive: true } })}`);
}

main()
  .catch((e) => {
    console.error("\n❌ Seed failed:", e.message);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
